version: '3.8'
services:
  dbt-clickhouse:
    build:
      context: .
      dockerfile: Dockerfile  # Custom Dockerfile if needed
    container_name: dbt-clickhouse-service
    environment:
      - DBT_PROFILES_DIR=/app/.dbt
    volumes:
      - ./dbt:/app
      - ./profiles.yml:/app/.dbt/profiles.yml
    command: >
      bash -c "
        dbt deps &&
        dbt seed &&
        dbt run &&
        dbt test
      "
    ports:
      - "8003:8000"
    networks:
      shared-network

networks:
  dbt_network:
    driver: bridge


networks:
  shared-network:
    external: true  # Specify that this network is managed externally (must exist in Docker)
