# Dockerfile

# Use a base image with Python 3.9
FROM python:3.9-slim

# Set environment variables
ENV DBT_PROFILES_DIR=/app/.dbt

# Set the working directory inside the container
WORKDIR /app/dbt

# Copy the dbt project files from the local directory to the container
COPY ./dbt /app/dbt

# Copy the profiles.yml file to the appropriate directory inside the container
COPY ./profiles.yml /app/.dbt/profiles.yml

# Install dbt and dbt-clickhouse dependencies
RUN pip install --no-cache-dir dbt-core dbt-clickhouse

# Define the command to run when the container starts
CMD ["bash", "-c", "dbt deps && dbt seed && dbt run && dbt test"]
